# Generated by Django 4.2.13 on 2026-04-30 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, help_text='Category for organizing templates', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Icon emoji or name', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False, help_text='System templates available to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_templates',
                'ordering': ['-is_favorite', '-usage_count', 'name'],
                'indexes': [models.Index(fields=['user', 'is_favorite'], name='note_templa_user_id_94a9a6_idx'), models.Index(fields=['category'], name='note_templa_categor_f51122_idx'), models.Index(fields=['is_system'], name='note_templa_is_syst_2358c7_idx')],
            },
        ),
    ]
